version: '3.1'
services:

  postgres-dashboard-db:
    image: postgres
    container_name: postgres-dashboard-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - target-data:/var/lib/postgresql/data




  app:
    container_name: personal-dashboard-backend
    image: rolandsall24/personal-dashboard-backend:1.0.0
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres-dashboard-db


volumes:
  target-data:
