spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RolandSall/personal-dashboard-backend-configuration.git
          search-paths:
            - 'local'
            - 'dev'
            - 'prod'

server:
  port: 8888

