spring:
  application:
    name: personal-dashboard
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://postgres-dashboard-db:5432/dashboard
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}