version: '3.5'
services:
  mongo:
    image: mongo
    container_name: todo-service-db
    restart: always
    ports:
      - 27017:27017
    networks:
      - default

  app:
    container_name: todo-service
    image: rolandsall24/todo-service:1.0.0
    build: ./
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - mongo

networks:
  default:
    driver: bridge