version: '3.1'
services:
  mongo:
    image: mongo
    container_name: todo-service-db
    restart: always
    ports:
      - 27017:27017

  app:
    container_name: todo-service
    image: rolandsall24/todo-service:1.0.0
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongo